use_frameworks!

target 'UIViewController-DisplayInDrawer_Example' do
  pod 'UIViewController-DisplayInDrawer', :path => '../'

  target 'UIViewController-DisplayInDrawer_Tests' do
    inherit! :search_paths

    
  end
end
